// <auto-generated />
using System;
using MainApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MainApplication.Migrations
{
    [DbContext(typeof(WarehouseContext))]
    [Migration("20240926080205_SeedTickets")]
    partial class SeedTickets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("MainApplication.Models.Chemical", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("WarehouseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Chemical");
                });

            modelBuilder.Entity("MainApplication.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DepotName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsValid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WarehouseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("MainApplication.Models.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WarehouseName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("MainApplication.Models.Chemical", b =>
                {
                    b.HasOne("MainApplication.Models.Warehouse", null)
                        .WithMany("Chemicals")
                        .HasForeignKey("WarehouseId");
                });

            modelBuilder.Entity("MainApplication.Models.Ticket", b =>
                {
                    b.HasOne("MainApplication.Models.Warehouse", "ShipmentDetails")
                        .WithMany()
                        .HasForeignKey("WarehouseId");

                    b.Navigation("ShipmentDetails");
                });

            modelBuilder.Entity("MainApplication.Models.Warehouse", b =>
                {
                    b.Navigation("Chemicals");
                });
#pragma warning restore 612, 618
        }
    }
}
